### ISSUE TITLE
Interpolated Strings

### ISSUE THREAD

**Issue by meany** [justinamiller/LiteStringBuilder#3]
Since C# v6, I've been using Interpolated Strings heavily.
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/interpolated

I don't know if it matters -- but I think it would be a good idea if you could add a benchmark for this as well.

**Comment by justinamiller** [comment]
Will add.

**Comment by justinamiller** [comment]
Check out Readme for results.
